version: "2.3"
services:

  zookeeper:
    ports:
      - 49801:49800
      - 49901:49900
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.12.0.jar=49800:/usr/share/jmx_exporter/zookeeper.yml
                  -javaagent:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar=port=49900,host=*
    volumes:
      - ./env_files/jolokia-jvm-1.6.2-agent.jar:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar:rw
      - ./env_files/jmx_prometheus_javaagent-0.12.0.jar:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.12.0.jar:rw
      - ./env_files/jmxexporter_configs/configs/zookeeper.yml:/usr/share/jmx_exporter/zookeeper.yml

  kafka1:
    volumes:
      - ./env_files/jolokia-jvm-1.6.2-agent.jar:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar:rw
      - ./env_files/jmxexporter_configs/configs/kafka.yml:/usr/share/jmx_exporter/kafka.yml
      - ./env_files/jmx_prometheus_javaagent-0.12.0.jar:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.12.0.jar
    ports:
      - 12093:12093
      - 49811:49800
      - 49911:49900
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,TOKEN:SASL_SSL,SSL:SSL,CLEAR:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9091,TOKEN://kafka1:10091,SSL://kafka1:11091,CLEAR://kafka1:12091,EXTERNAL://localhost:12093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf
                  -Djavax.net.ssl.trustStore=/etc/kafka/secrets/kafka.kafka1.truststore.jks
                  -Djavax.net.ssl.trustStorePassword=confluent
                  -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.12.0.jar=49800:/usr/share/jmx_exporter/kafka.yml
                  -javaagent:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar=port=49900,host=*

  kafka2:
    volumes:
      - ./env_files/jolokia-jvm-1.6.2-agent.jar:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar:rw
      - ./env_files/jmxexporter_configs/configs/kafka.yml:/usr/share/jmx_exporter/kafka.yml
      - ./env_files/jmx_prometheus_javaagent-0.12.0.jar:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.12.0.jar
    ports:
      - 12094:12094
      - 49812:49800
      - 49912:49900
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,TOKEN:SASL_SSL,SSL:SSL,CLEAR:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,TOKEN://kafka2:10092,SSL://kafka2:11092,CLEAR://kafka2:12092,EXTERNAL://localhost:12094 
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf
                  -Djavax.net.ssl.trustStore=/etc/kafka/secrets/kafka.kafka1.truststore.jks
                  -Djavax.net.ssl.trustStorePassword=confluent
                  -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.12.0.jar=49800:/usr/share/jmx_exporter/kafka.yml
                  -javaagent:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar=port=49900,host=*

  connect:
    volumes:
      - ./env_files/jolokia-jvm-1.6.2-agent.jar:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar:rw
      - ./env_files/jmx_prometheus_javaagent-0.12.0.jar:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.12.0.jar
      - ./env_files/jmxexporter_configs/configs/connect.yml:/usr/share/jmx_exporter/connect.yml
    ports:
      - 49921:49900
      - 49821:49800
    environment:
      # KAFKA_OPTS required for ReplicatorMonitoringExtension
      KAFKA_OPTS: -javaagent:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar=port=49900,host=*
                  -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.12.0.jar=49800:/usr/share/jmx_exporter/connect.yml
      CONNECT_PLUGIN_PATH: "/usr/share/java,/connect-plugins,/usr/share/confluent-hub-components"
    command: "bash -c 'sleep 10 && \
              confluent-hub install splunk/kafka-connect-splunk:1.2.0 --no-prompt && \
              cp /usr/share/java/kafka-connect-replicator/replicator-rest-extension-*.jar /etc/kafka-connect/jars/ && \
              /etc/confluent/docker/run'"

  ksql-server:
    volumes:
      - ./env_files/jolokia-jvm-1.6.2-agent.jar:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar:rw
    ports:
      - 49931:49900
    environment:
      KSQL_OPTS: -javaagent:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar=port=49900,host=*

  elasticsearch:
    cpus: 0.8

  kafkametricsexporter:
    image: abhiwalia/kafkajmxexporter:0.3
    container_name: kafkametricsexporter
    cpus: 0.2
    restart: "always"
    depends_on:
      - kibana
    command: [ #Core JMX Metrics Gather Configurations
              "--jmx-zk-server","http://zookeeper:49900/"
              ,"--jmx-kafka-server","http://kafka1:49900/"
              ,"--jmx-kafka-server","http://kafka2:49900/"
              ,"--jmx-connect-server","http://connect:49900/"
              ,"--jmx-ksql-server","http://ksql-server:49900/"
              # Connect REST data ingestion
              ,"--enable-connect-rest-source"
              ,"--connect-rest-endpoint","https://connect:8083/"
              ,"--enable-connect-rest-auth"
              ,"--connect-rest-auth-user","superUser"
              ,"--connect-rest-auth-pass","superUser"
              # Enable ES Data Sink to Gather all the JMX data and stream it to Elastic
              ,"--enable-elastic-sink"
              ,"--es-url","http://elasticsearch:9200/"
              ,"--kibana-url","http://kibana:5601/"
              ,"--es-bulk-url-timeout","60"
              # Enable Kafka Data Sink to gather all the data and stream it to Kafka
              ,"--enable-kafka-sink"
              ,"--kafka-topic-name","jmx_data_ingestion_pipeline"
              ,"--kafka-conn-props","bootstrap.servers=kafka1:12091"
              ,"--kafka-conn-props","client.id=JMX_Data_Producer"
              ,"--kafka-conn-props","compression.type=snappy"
              ,"--kafka-conn-props","retries=10"
              ,"--kafka-conn-props","linger.ms=50"
    ]

  # splunk:
  #   image: splunk/splunk:latest
  #   restart: always
  #   container_name: "splunk"
  #   depends_on: 
  #     - elasticsearch
  #   ports:
  #     - 7080:8000  #SplunkWeb UI
  #     - 7081:8088  #HTTP Event Collector (HEC)
  #   environment:
  #     SPLUNK_START_ARGS: --accept-license
  #     SPLUNK_PASSWORD: confluent
  #     KAFKA_SINK: 66e2d730-5bb5-4d3d-83c5-393ef9f2e32a
  #     TZ: "America/Los_Angeles"
  #   volumes:
  #     - ./scripts/dashboard/splunk_confluent_platform_dashboard.xml:/opt/splunk/etc/apps/search/local/data/ui/views/confluent_platform_dashboard.xml:rw

  # prometheus:
  #   image: prom/prometheus
  #   restart: always
  #   container_name: prometheus
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 7070:9090
  #   volumes:
  #     - ./env_files/jmxexporter_configs/configs/prometheus.yml:/etc/prometheus/prometheus.yml

  # grafana:
  #   image: grafana/grafana
  #   restart: always
  #   container_name: grafana
  #   depends_on: 
  #     - prometheus
  #   ports:
  #     - 7071:3000
  #   volumes:
  #     - ./env_files/jmxexporter_configs/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasource.yml
  #     - ./env_files/jmxexporter_configs/grafana/dashboards:/etc/grafana/provisioning/dashboards
  #   env_file:
  #     - ./env_files/jmxexporter_configs/grafana/config.monitoring

  # control-center:
  #   environment:
  #     CONTROL_CENTER_CONNECT_CONNECT1_CLUSTER: https://connect:8083

  # control-center:
  #   volumes:
  #     - ./env_files/jolokia-jvm-1.6.2-agent.jar:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar:rw

  # schemaregistry:
  #   volumes:
  #     - ./env_files/jolokia-jvm-1.6.2-agent.jar:/usr/share/jolokia/jolokia-jvm-1.6.2-agent.jar:rw