{
 "title": "Kafka Connect Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "JVM Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance, area) (jvm_memory_bytes_used{job=\"KafkaConnect\"}) /1024 /1024",
     "legendFormat": "{{instance}} >> {{area}} usage"
    }
   ]
  },
  {
   "title": "Total Connectors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum without (instance) (kafka_connect_worker_connector_count)",
     "legendFormat": "Total Connectors"
    }
   ]
  },
  {
   "title": "Time taken for last Rebalance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_rebalance_avg_time_ms"
    }
   ]
  },
  {
   "title": "JVM Thread count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total Extrinsic Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "sum by (clientId) (kafka_connect_connect_connection_count)",
     "legendFormat": "Total Extrinsic Connections"
    }
   ]
  },
  {
   "title": "Time Since Last Connect Rebalance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "avg by (job) (kafka_connect_worker_rebalance_time_since_last_rebalance_ms) /1000 "
    }
   ]
  },
  {
   "title": "Connector Task Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job) (kafka_connect_worker_connector_total_task_count)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Task Error Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by ( connector) (kafka_connect_task_error_total_record_errors) > 0",
     "legendFormat": "{{connector}} Record Errors"
    },
    {
     "expr": "sum by ( connector) (kafka_connect_task_error_total_record_failures) > 0",
     "legendFormat": "{{connector}} Record Failures"
    },
    {
     "expr": "sum by ( connector) (kafka_connect_task_error_total_records_skipped) > 0",
     "legendFormat": "{{connector}} Record Failures"
    }
   ]
  },
  {
   "title": "Connect IO Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (clientId,instance) (kafka_connect_connect_io_ratio)",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Average Batch Size at Connector Level",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg by (connector) (kafka_connect_connector_task_batch_size_avg))",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Top 10 Average Batch Size at Task level",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, avg by (connector,task) (kafka_connect_connector_task_batch_size_avg))",
     "legendFormat": "{{connector}}: Task {{task}}"
    }
   ]
  },
  {
   "title": "Top 5 Clients for most incoming/outgoing data rate (in KBps)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (clientId) (rate(kafka_connect_connect_node_outgoing_byte_total[1m]) + rate(kafka_connect_connect_node_incoming_byte_total[1m])) /1024 )",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Top 5 Connectors by Source Record Poll Rate ( per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (connector) (rate(kafka_connect_source_task_source_record_poll_total[1m])))",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Top 5 Task outliers for source poll batch average size (in ms)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "topk(5 , avg by (connector, task) (kafka_connect_source_task_poll_batch_avg_time_ms))",
     "legendFormat": "Connector: {{connector}} >> Task: {{task}}"
    }
   ]
  }
 ]
}