{
 "title": "Kafka Brokers Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ServerType", "label": "Server Type", "query": "label_values(job)" },
   { "name": "Instance", "label": "InstanceName", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Available Brokers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (count(kafka_brokers_controller_kafkacontroller_activecontrollercount))",
     "legendFormat": "Available Brokers"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kafka_brokers_network_socketserver_networkprocessoravgidlepercent)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (kafka_brokers_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Total Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (kafka_brokers_controller_kafkacontroller_globaltopiccount)",
     "legendFormat": "Topic Count"
    }
   ]
  },
  {
   "title": "Total Partitions",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (kafka_brokers_controller_kafkacontroller_globalpartitioncount)",
     "legendFormat": "Topic Patition Count"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,area) (jvm_memory_bytes_used{job=\"KafkaBrokers\"})",
     "legendFormat": "{{instance}} >> {{area}}"
    }
   ]
  },
  {
   "title": "GC Collection times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"KafkaBrokers\"}[1m])",
     "legendFormat": "{{instance}} >> {{gc}}"
    }
   ]
  },
  {
   "title": "Offline Log Directory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (kafka_brokers_log_logmanager_offlinelogdirectorycount)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kafka_brokers_server_replicamanager_underreplicatedpartitions)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Offline Patitions Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (job) (kafka_brokers_controller_kafkacontroller_offlinepartitionscount)",
     "legendFormat": "Offline Patitions Count"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(kafka_brokers_server_brokertopicmetrics_bytesin_total[1m]) + rate(kafka_brokers_server_brokertopicmetrics_bytesout_total[1m]))",
     "legendFormat": "Total Incoming Msg Rate"
    },
    {
     "expr": "sum by (instance) (rate(kafka_brokers_server_brokertopicmetrics_bytesin_total[1m]) + rate(kafka_brokers_server_brokertopicmetrics_bytesout_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages in per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (topk(3 , (rate(kafka_brokers_server_brokertopicmetrics_messagesin_total{topic != \"\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Messages in per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (topk(3 , (rate(kafka_brokers_server_brokertopicmetrics_messagesin_total{topic != \"\"}[1m]))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Topic Size",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_brokers_log_log_totalsize) > 0"
    }
   ]
  },
  {
   "title": "Broker IO Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,request) (kafka_brokers_network_requestmetrics_requestqueuetimems{request=~\"Produce|FetchConsumer|FetchFollower\"})",
     "legendFormat": "{{instance}} >> {{request}}"
    }
   ]
  },
  {
   "title": "Bytes in per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (topk(3 , (rate(kafka_brokers_server_brokertopicmetrics_bytesin_total{topic != \"\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Bytes in per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (topk(3 , (rate(kafka_brokers_server_brokertopicmetrics_bytesin_total{topic != \"\"}[1m]))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Incoming msg rate per topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (topk(3, rate(kafka_brokers_server_brokertopicmetrics_messagesin_total{topic != \"\"}[1m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Per Broker Partition Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kafka_brokers_server_replicamanager_partitioncount)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ISR Management",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_brokers_server_replicamanager_isrshrinks_total[1m])",
     "legendFormat": "{{instance}} ISR Shrink"
    },
    {
     "expr": "rate(kafka_brokers_server_replicamanager_isrexpands_total[1m])",
     "legendFormat": "{{instance}} ISR Expand"
    }
   ]
  },
  {
   "title": "Bytes out per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (topk(3 , (rate(kafka_brokers_server_brokertopicmetrics_bytesout_total{topic != \"\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Bytes in per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (topk(3 , (rate(kafka_brokers_server_brokertopicmetrics_bytesout_total{topic != \"\"}[1m]))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker Client Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,request) (rate(kafka_brokers_network_requestmetrics_requests_total{request=~\"Produce|FetchConsumer|FetchFollower\"}[1m]))",
     "legendFormat": "{{instance}} >> {{request}}"
    }
   ]
  }
 ]
}