{
 "title": "Confluent Platform ZooKeeper Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ServerURL", "label": "Server URL", "query": "label_values(instance)" },
   { "name": "ServerName", "label": "Server Name", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Data Directory Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_DataDirSize{instance=~\"$ServerName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", instance=~\"$ServerName\"}",
     "legendFormat": "On Heap Usage: {{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\", instance=~\"$ServerName\"}",
     "legendFormat": "Off Heap Usage: {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Alive Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_NumAliveConnections{instance=~\"$ServerName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Packet Tx/Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_PacketsReceived{instance=~\"$ServerName\"} + zookeeper_PacketsSent{instance=~\"$ServerName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "repeat": "ServerName",
   "targets": [
    {
     "expr": "zookeeper_AvgRequestLatency{instance=~\"$ServerName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Count and Watch Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_NodeCount", "legendFormat": "Node Count: {{instance}}" },
    { "expr": "zookeeper_WatchCount", "legendFormat": "Watch Count: {{instance}}" }
   ]
  }
 ]
}